[workspace]
members = [
    "collections",
    "control_flow",
    "enums",
    "errors",
    "exercises",
    "functions",
    "generics",
    "guessing_game",
    "hello_cargo",
    "lifetimes",
    "loops",
    "ownership",
    "restaurant",
    "slices",
    "structs",
    "structs_example",
    "traits",
    "variables"
]
